//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfConstractions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUPassport_State
    {
        public System.Guid id { get; set; }
        public System.Guid GUPassport_ID { get; set; }
        public string State { get; set; }
        public System.DateTimeOffset startdate { get; set; }
        public System.DateTimeOffset upserted { get; set; }
        public System.Guid Sotr_ID { get; set; }
        public byte[] tsc { get; set; }
        public Nullable<System.Guid> NextID { get; set; }
    
        public virtual GUPassport GUPassport { get; set; }
    }
}
