//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfConstractions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUPassport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUPassport()
        {
            this.GUPassport_Sites = new HashSet<GUPassport_Site>();
            this.GUPassport_States = new HashSet<GUPassport_State>();
            this.GUPassports1 = new HashSet<GUPassport>();
            this.GUPassports11 = new HashSet<GUPassport>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> prev { get; set; }
        public Nullable<System.Guid> next { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public System.DateTimeOffset insertdate { get; set; }
        public Nullable<System.DateTimeOffset> updatedate { get; set; }
        public System.Guid Sotr_ID { get; set; }
        public byte[] tsc { get; set; }
        public string UNOM { get; set; }
        public System.Guid HouseID { get; set; }
        public System.Guid AdmidArea_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeography WGS84 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry EGKO { get; set; }
        public System.Guid Ground_Type_ID { get; set; }
        public string Visibility { get; set; }
        public string Sidewalk_width { get; set; }
        public string Condition { get; set; }
        public string Patency { get; set; }
        public string Reconstruction { get; set; }
        public string Closed_loop { get; set; }
        public string Electricity_connection { get; set; }
        public byte[] Foto { get; set; }
        public byte[] Plan { get; set; }
    
        public virtual AdminArea AdminArea { get; set; }
        public virtual Ground_Type Ground_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUPassport_Site> GUPassport_Sites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUPassport_State> GUPassport_States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUPassport> GUPassports1 { get; set; }
        public virtual GUPassport GUPassport1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUPassport> GUPassports11 { get; set; }
        public virtual GUPassport GUPassport2 { get; set; }
    }
}
