//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfConstractions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormativeDocument
    {
        public System.Guid NORMDOCID { get; set; }
        public string DOCNAME { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public string DOCNUM { get; set; }
        public long DOCTYPE { get; set; }
        public Nullable<int> DOCIMGID { get; set; }
    
        public virtual NormativeDocument NormativeDocument1 { get; set; }
        public virtual NormativeDocument NormativeDocument2 { get; set; }
        public virtual NormativeDocumentType NormativeDocumentType { get; set; }
    }
}
