namespace InfConstractionsDX.Modules.Views
{
    using System.Data.Entity.Infrastructure;
    using System;
    using System.Collections.Generic;
    using InfConstractions.Models;
    using ViewModels;
    using DevExpress.XtraGrid.Views.Grid;
    using System.Windows.Controls;
    using System.Drawing;

    public partial class ProverkaGUView : UserControl
    {
        public ProverkaGUView()
        {
            InitializeComponent();
        }
        private void TableView_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (DataContext != null)
            {
                List<proverkaGU> l = new List<proverkaGU>();
                DbChangeTracker tr = ((ProverkaGUViewModel)DataContext).Context.ChangeTracker;
                tr.DetectChanges();
                if (tr.HasChanges())
                {
                    foreach (DbEntityEntry p in tr.Entries())
                    {
                        if (p.State == System.Data.Entity.EntityState.Modified)
                        {
                            ((proverkaGU)p.Entity).updated = DateTimeOffset.Now;
                            l.Add((proverkaGU)p.Entity);
                        }
                    }
                ((ProverkaGUViewModel)DataContext).cmSaveChanges();
                    foreach (proverkaGU t in l)
                    {
                        ((ProverkaGUViewModel)DataContext).Context.Entry<proverkaGU>(t).Reload();
                        ((ProverkaGUViewModel)DataContext).Context.proverkaGUs.Attach(t);
                    }
                }
            }
        }

        private void btnSave_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            gridMain.RefreshData();
        }

        private void gridMain_AutoGeneratedColumns(object sender, System.Windows.RoutedEventArgs e)
        {
            cLink.BestFitWidth = 30;
        }

        private void GridView_RowStyle(object sender, RowStyleEventArgs e)
        {
            DevExpress.XtraGrid.Views.Grid.GridView View = sender as DevExpress.XtraGrid.Views.Grid.GridView;
            if (e.RowHandle >= 0)
            {
                var newPassport = View.GetRowCellDisplayText(e.RowHandle, View.Columns["newPassport"]);
                if (newPassport != null)
                {
                    e.Appearance.BackColor = Color.Salmon;
                    e.Appearance.BackColor2 = Color.SeaShell;
                }
            }
        }
    
    }



    }

