//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfConstractions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminArea()
        {
            this.AdminArea1 = new HashSet<AdminArea>();
            this.GUPassports = new HashSet<GUPassport>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Parent_ID { get; set; }
        public string fullName { get; set; }
        public string shortName { get; set; }
        public string OKATO { get; set; }
        public Nullable<int> global_id { get; set; }
        public string Kod { get; set; }
        public string Latin_fullName { get; set; }
        public string Type { get; set; }
        public System.Data.Entity.Spatial.DbGeography geoData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminArea> AdminArea1 { get; set; }
        public virtual AdminArea AdminArea2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUPassport> GUPassports { get; set; }
    }
}
