//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfConstractions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLAddressObjectsFull
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PARENTGUID { get; set; }
        public string itemAddress { get; set; }
        public string fullAddress { get; set; }
    }
}
